$('.owl-carousel').owlCarousel({
    loop:false,
    margin:10,
    nav:false,
    responsive:{
        0:{
            item:1
        },
        600:{
            item:3
        },
        1000:{
            items:5
        }
    }
})